name: Deploy Wiki

on:
  push:
    paths:
      # Trigger only when node api directory changes
      - 'src/**'
    branches:
      # And only on master branch
      - main

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: c-hive/gha-yarn-cache@v2
    - name: Install NodeJs dependencies
      run: yarn install
    - name: Build Docs
      run: yarn generate-docs

    - name: Publish Docs Changes
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
      with:
        dir: docs
        branch: gh-pages
        token: ${{ secrets.ACCESS_TOKEN }}
