name: Deploy Wiki

on:
  push:
    paths:
      # Trigger only when node api directory changes
      - 'src/**'
    branches:
      # And only on master branch
      - main

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: c-hive/gha-yarn-cache@v2
    - name: Install NodeJs dependencies
      run: yarn install
    - name: Build Docs
      run: yarn generate-docs

    - name: Publish Docs Changes
      uses: peaceiris/actions-gh-pages@v3
      # If you're changing the branch from main,
      # also change the `main` in `refs/heads/main`
      # below accordingly.
      # if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
