name: Deploy Wiki

on:
  push:
    paths:
      # Trigger only when node api directory changes
      - 'src/**'
    branches:
      # And only on master branch
      - main

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: c-hive/gha-yarn-cache@v2
    - name: Install NodeJs dependencies
      run: yarn install
    - name: Build Docs
      run: yarn generate-docs

    - name: Publish Docs Changes
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs # The folder the action should deplo
